In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
# Numpy's main datatype is ndarray (n-dimensional-array).
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3],
                [4,5,6.5]])

a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15],[16,17,18]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape # since it's (1,3) 

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# what if i were to index it, tho?
a2[1]

array([4. , 5. , 6.5])

In [18]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [19]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# create a DataFRame from Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [3]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.70510063, 0.55602564, 0.48033976],
       [0.63573376, 0.65705646, 0.43278342],
       [0.05409045, 0.52935971, 0.69317877],
       [0.49773276, 0.03541913, 0.27244712],
       [0.17890589, 0.1340284 , 0.40971788]])

In [7]:
# Pseudo-random numbers
np.random.seed(seed=0) # helps numbers be re-producable. 
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing Arrays and Matricies

In [8]:
# how to find unique elements in numpy arrays
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a1[0]

1

In [13]:
a2[0]

array([1. , 2. , 3.3])

## Manipulating and Comparing Arrays

### Arithmetic

In [14]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [16]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [17]:
a1 + ones

array([2., 3., 4.])

In [18]:
a1 - ones

array([0., 1., 2.])

In [19]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [20]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [21]:
# how can you reshape a2 so that a2 * a3 is possible?
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [22]:
a1 / ones

array([1., 2., 3.])

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [39]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [40]:
# broadcasting a2 so that a2*a3 is possible:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [41]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [42]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [43]:
# Transpose = switches axis
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

## Dot Product

In [44]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [45]:
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [46]:
# Element-wise multiplication (Hadamard Product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [47]:
np.dot(mat1, mat2) # error because dimensions don't 

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [48]:
# Transpose mat1:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [49]:
np.dot(mat1.T, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

### Comparison Operators

In [5]:
a1

array([1, 2, 3])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [9]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [10]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

## Sorting Arrays

In [13]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[6, 9, 0, 0, 6],
       [6, 0, 9, 3, 9],
       [4, 3, 8, 0, 1]])

In [14]:
np.sort(random_array)

array([[0, 0, 6, 6, 9],
       [0, 3, 6, 9, 9],
       [0, 1, 3, 4, 8]])

In [15]:
# sorts indices
np.argsort(random_array)

array([[2, 3, 0, 4, 1],
       [1, 3, 0, 2, 4],
       [3, 4, 1, 0, 2]], dtype=int64)

In [16]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [17]:
np.argmin(a1)

0

In [18]:
np.argmax(a1)

2

In [19]:
np.argmax(random_array)

1

### Practical Example

<img src="../../Data/Images/panda.png"/>

In [23]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("../../Data/Images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [25]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [26]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

In [27]:
car = imread("../../Data/Images/car-photo.png")
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

In [28]:
dog = imread("../../Data/Images/dog-photo.png")
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)

In [31]:
dog.ndim, dog.shape, dog.size

(3, (432, 575, 4), 993600)